const PDFDocument = require('pdfkit');

const generateSummaryPdf = ({ title, subjectName, notebookName, summaryText }) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, autoFirstPage: true, bufferPages: true });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      doc.fontSize(20).font('Helvetica-Bold').fillColor('black').text(title || 'Notebook Summary', { align: 'center' });
      doc.moveDown(0.5);
      
      const subtitleText = [];
      if (subjectName) subtitleText.push(`Subject: ${subjectName}`);
      if (notebookName) subtitleText.push(`Notebook: ${notebookName}`);
      if (subtitleText.length > 0) {
        doc.fontSize(12).font('Helvetica').fillColor('gray').text(subtitleText.join(' | '), { align: 'center' });
        doc.moveDown(0.5);
      }
      
      doc.fontSize(10).font('Helvetica').fillColor('gray').text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);
      
      // Horizontal Rule
      doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e2e8f0').stroke();
      doc.moveDown(1.5);

      // Body text
      doc.fillColor('black').fontSize(11).font('Helvetica');
      
      const lines = summaryText.split('\n');
      lines.forEach(line => {
        if (!line.trim()) {
          doc.moveDown(0.5);
          return;
        }

        // Measure leading spaces for indentation
        const leadingSpaces = line.match(/^ */)[0].length;
        let indent = leadingSpaces * 4; // roughly 4 points per space
        
        let text = line.trim();

        // Check for headers
        let isHeader = false;
        if (text.startsWith('### ')) {
          isHeader = true;
          text = text.substring(4);
          doc.font('Helvetica-Bold').fontSize(13);
        } else if (text.startsWith('## ')) {
          isHeader = true;
          text = text.substring(3);
          doc.font('Helvetica-Bold').fontSize(15);
        } else if (text.startsWith('# ')) {
          isHeader = true;
          text = text.substring(2);
          doc.font('Helvetica-Bold').fontSize(17);
        } else {
          doc.font('Helvetica').fontSize(11);
        }

        // Remove bold/italic markdown symbols
        text = text.replace(/\*\*(.*?)\*\*/g, '$1');
        text = text.replace(/\*(.*?)\*/g, '$1');
        text = text.replace(/__(.*?)__/g, '$1');
        text = text.replace(/_(.*?)_/g, '$1');
        
        // Handle bullet points
        if (text.startsWith('- ') || text.startsWith('* ')) {
          text = '• ' + text.substring(2);
          indent += 10;
        }
        
        // Handle numbered lists indentation
        if (/^\d+\.\s/.test(text)) {
           indent += 10;
        }

        // Render the text line
        doc.text(text, {
          align: 'left',
          lineGap: 4,
          indent: indent
        });
        
        if (isHeader) {
          doc.moveDown(0.3);
        }
      });

      // Add footers to all pages
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        const bottom = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;
        doc.fillColor('gray').fontSize(9).text(
          `Generated by Aethon - Page ${i + 1}`,
          0.5 * (doc.page.width - 200),
          doc.page.height - 30,
          { width: 200, align: 'center', lineBreak: false }
        );
        doc.page.margins.bottom = bottom;
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateSummaryPdf };
